//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.14 at 04:39:10 PM BST 
//


package com.carnifex.rsyncmover.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.carnifex.rsyncmover.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.carnifex.rsyncmover.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RsyncMover }
     * 
     */
    public RsyncMover createRsyncMover() {
        return new RsyncMover();
    }

    /**
     * Create an instance of {@link RsyncMover.Notification }
     * 
     */
    public RsyncMover.Notification createRsyncMoverNotification() {
        return new RsyncMover.Notification();
    }

    /**
     * Create an instance of {@link RsyncMover.Notification.Agent }
     * 
     */
    public RsyncMover.Notification.Agent createRsyncMoverNotificationAgent() {
        return new RsyncMover.Notification.Agent();
    }

    /**
     * Create an instance of {@link RsyncMover.Notification.Agent.Params }
     * 
     */
    public RsyncMover.Notification.Agent.Params createRsyncMoverNotificationAgentParams() {
        return new RsyncMover.Notification.Agent.Params();
    }

    /**
     * Create an instance of {@link RsyncMover.Servers }
     * 
     */
    public RsyncMover.Servers createRsyncMoverServers() {
        return new RsyncMover.Servers();
    }

    /**
     * Create an instance of {@link RsyncMover.Servers.Server }
     * 
     */
    public RsyncMover.Servers.Server createRsyncMoverServersServer() {
        return new RsyncMover.Servers.Server();
    }

    /**
     * Create an instance of {@link RsyncMover.Servers.Server.Directories }
     * 
     */
    public RsyncMover.Servers.Server.Directories createRsyncMoverServersServerDirectories() {
        return new RsyncMover.Servers.Server.Directories();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers }
     * 
     */
    public RsyncMover.Movers createRsyncMoverMovers() {
        return new RsyncMover.Movers();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover }
     * 
     */
    public RsyncMover.Movers.Mover createRsyncMoverMoversMover() {
        return new RsyncMover.Movers.Mover();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover.MoveOperators }
     * 
     */
    public RsyncMover.Movers.Mover.MoveOperators createRsyncMoverMoversMoverMoveOperators() {
        return new RsyncMover.Movers.Mover.MoveOperators();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover.MoveOperators.MoveOperator }
     * 
     */
    public RsyncMover.Movers.Mover.MoveOperators.MoveOperator createRsyncMoverMoversMoverMoveOperatorsMoveOperator() {
        return new RsyncMover.Movers.Mover.MoveOperators.MoveOperator();
    }

    /**
     * Create an instance of {@link RsyncMover.Watches }
     * 
     */
    public RsyncMover.Watches createRsyncMoverWatches() {
        return new RsyncMover.Watches();
    }

    /**
     * Create an instance of {@link RsyncMover.EmailSummary }
     * 
     */
    public RsyncMover.EmailSummary createRsyncMoverEmailSummary() {
        return new RsyncMover.EmailSummary();
    }

    /**
     * Create an instance of {@link RsyncMover.Audit }
     * 
     */
    public RsyncMover.Audit createRsyncMoverAudit() {
        return new RsyncMover.Audit();
    }

    /**
     * Create an instance of {@link RsyncMover.WebServer }
     * 
     */
    public RsyncMover.WebServer createRsyncMoverWebServer() {
        return new RsyncMover.WebServer();
    }

    /**
     * Create an instance of {@link RsyncMover.Notification.Agent.NotifyOnTypes }
     * 
     */
    public RsyncMover.Notification.Agent.NotifyOnTypes createRsyncMoverNotificationAgentNotifyOnTypes() {
        return new RsyncMover.Notification.Agent.NotifyOnTypes();
    }

    /**
     * Create an instance of {@link RsyncMover.Notification.Agent.Params.Param }
     * 
     */
    public RsyncMover.Notification.Agent.Params.Param createRsyncMoverNotificationAgentParamsParam() {
        return new RsyncMover.Notification.Agent.Params.Param();
    }

    /**
     * Create an instance of {@link RsyncMover.Servers.Server.Agents }
     * 
     */
    public RsyncMover.Servers.Server.Agents createRsyncMoverServersServerAgents() {
        return new RsyncMover.Servers.Server.Agents();
    }

    /**
     * Create an instance of {@link RsyncMover.Servers.Server.Directories.Directory }
     * 
     */
    public RsyncMover.Servers.Server.Directories.Directory createRsyncMoverServersServerDirectoriesDirectory() {
        return new RsyncMover.Servers.Server.Directories.Directory();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover.SubsonicScanner }
     * 
     */
    public RsyncMover.Movers.Mover.SubsonicScanner createRsyncMoverMoversMoverSubsonicScanner() {
        return new RsyncMover.Movers.Mover.SubsonicScanner();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover.Agents }
     * 
     */
    public RsyncMover.Movers.Mover.Agents createRsyncMoverMoversMoverAgents() {
        return new RsyncMover.Movers.Mover.Agents();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover.Patterns }
     * 
     */
    public RsyncMover.Movers.Mover.Patterns createRsyncMoverMoversMoverPatterns() {
        return new RsyncMover.Movers.Mover.Patterns();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover.DontMatchPatterns }
     * 
     */
    public RsyncMover.Movers.Mover.DontMatchPatterns createRsyncMoverMoversMoverDontMatchPatterns() {
        return new RsyncMover.Movers.Mover.DontMatchPatterns();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover.DontMatchMoverByName }
     * 
     */
    public RsyncMover.Movers.Mover.DontMatchMoverByName createRsyncMoverMoversMoverDontMatchMoverByName() {
        return new RsyncMover.Movers.Mover.DontMatchMoverByName();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover.Extensions }
     * 
     */
    public RsyncMover.Movers.Mover.Extensions createRsyncMoverMoversMoverExtensions() {
        return new RsyncMover.Movers.Mover.Extensions();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover.AdditionalArguments }
     * 
     */
    public RsyncMover.Movers.Mover.AdditionalArguments createRsyncMoverMoversMoverAdditionalArguments() {
        return new RsyncMover.Movers.Mover.AdditionalArguments();
    }

    /**
     * Create an instance of {@link RsyncMover.Movers.Mover.MoveOperators.MoveOperator.AdditionalArguments }
     * 
     */
    public RsyncMover.Movers.Mover.MoveOperators.MoveOperator.AdditionalArguments createRsyncMoverMoversMoverMoveOperatorsMoveOperatorAdditionalArguments() {
        return new RsyncMover.Movers.Mover.MoveOperators.MoveOperator.AdditionalArguments();
    }

}
