//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 09:48:04 PM BST 
//


package com.carnifex.rsyncmover.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="watches"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="watch" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="movers"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="moveFiles" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="deleteDuplicateFiles" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="useDefaultMatching" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="movedFilePermissions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="mover" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="targetDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="patterns" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="dontMatchPatterns" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="extensions" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="partialMatch" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="moveOperation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="servers"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="downloadFiles" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="movedFilePermissions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="minimumFreeSpaceToDownload" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="mustMatchMoverForDownload" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="removePassivatedFilesIfNoLongerExistOnServer" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="passivateLocation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="depassivateEachTime" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="updateIntervalMinutes" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="server" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="pass" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="directories"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="directory" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="directory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="realDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="hostKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="logs"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="debug" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="emailSummary"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="emailReport" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="sendEmailAt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="webServer"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="webServer" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "watches",
    "movers",
    "servers",
    "logs",
    "emailSummary",
    "webServer"
})
@XmlRootElement(name = "rsyncMover")
public class RsyncMover {

    @XmlElement(required = true)
    protected RsyncMover.Watches watches;
    @XmlElement(required = true)
    protected RsyncMover.Movers movers;
    @XmlElement(required = true)
    protected RsyncMover.Servers servers;
    @XmlElement(required = true)
    protected RsyncMover.Logs logs;
    @XmlElement(required = true)
    protected RsyncMover.EmailSummary emailSummary;
    @XmlElement(required = true)
    protected RsyncMover.WebServer webServer;

    /**
     * Gets the value of the watches property.
     * 
     * @return
     *     possible object is
     *     {@link RsyncMover.Watches }
     *     
     */
    public RsyncMover.Watches getWatches() {
        return watches;
    }

    /**
     * Sets the value of the watches property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsyncMover.Watches }
     *     
     */
    public void setWatches(RsyncMover.Watches value) {
        this.watches = value;
    }

    /**
     * Gets the value of the movers property.
     * 
     * @return
     *     possible object is
     *     {@link RsyncMover.Movers }
     *     
     */
    public RsyncMover.Movers getMovers() {
        return movers;
    }

    /**
     * Sets the value of the movers property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsyncMover.Movers }
     *     
     */
    public void setMovers(RsyncMover.Movers value) {
        this.movers = value;
    }

    /**
     * Gets the value of the servers property.
     * 
     * @return
     *     possible object is
     *     {@link RsyncMover.Servers }
     *     
     */
    public RsyncMover.Servers getServers() {
        return servers;
    }

    /**
     * Sets the value of the servers property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsyncMover.Servers }
     *     
     */
    public void setServers(RsyncMover.Servers value) {
        this.servers = value;
    }

    /**
     * Gets the value of the logs property.
     * 
     * @return
     *     possible object is
     *     {@link RsyncMover.Logs }
     *     
     */
    public RsyncMover.Logs getLogs() {
        return logs;
    }

    /**
     * Sets the value of the logs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsyncMover.Logs }
     *     
     */
    public void setLogs(RsyncMover.Logs value) {
        this.logs = value;
    }

    /**
     * Gets the value of the emailSummary property.
     * 
     * @return
     *     possible object is
     *     {@link RsyncMover.EmailSummary }
     *     
     */
    public RsyncMover.EmailSummary getEmailSummary() {
        return emailSummary;
    }

    /**
     * Sets the value of the emailSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsyncMover.EmailSummary }
     *     
     */
    public void setEmailSummary(RsyncMover.EmailSummary value) {
        this.emailSummary = value;
    }

    /**
     * Gets the value of the webServer property.
     * 
     * @return
     *     possible object is
     *     {@link RsyncMover.WebServer }
     *     
     */
    public RsyncMover.WebServer getWebServer() {
        return webServer;
    }

    /**
     * Sets the value of the webServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsyncMover.WebServer }
     *     
     */
    public void setWebServer(RsyncMover.WebServer value) {
        this.webServer = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="emailReport" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="sendEmailAt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "emailReport",
        "to",
        "from",
        "sendEmailAt"
    })
    public static class EmailSummary {

        protected boolean emailReport;
        @XmlElement(required = true)
        protected String to;
        @XmlElement(required = true)
        protected String from;
        @XmlElement(required = true)
        protected String sendEmailAt;

        /**
         * Gets the value of the emailReport property.
         * 
         */
        public boolean isEmailReport() {
            return emailReport;
        }

        /**
         * Sets the value of the emailReport property.
         * 
         */
        public void setEmailReport(boolean value) {
            this.emailReport = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrom(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the sendEmailAt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSendEmailAt() {
            return sendEmailAt;
        }

        /**
         * Sets the value of the sendEmailAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSendEmailAt(String value) {
            this.sendEmailAt = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="debug" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "error",
        "debug"
    })
    public static class Logs {

        @XmlElement(required = true)
        protected String error;
        @XmlElement(required = true)
        protected String debug;

        /**
         * Gets the value of the error property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getError() {
            return error;
        }

        /**
         * Sets the value of the error property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setError(String value) {
            this.error = value;
        }

        /**
         * Gets the value of the debug property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDebug() {
            return debug;
        }

        /**
         * Sets the value of the debug property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDebug(String value) {
            this.debug = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="moveFiles" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="deleteDuplicateFiles" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="useDefaultMatching" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="movedFilePermissions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="mover" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="targetDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="patterns" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="dontMatchPatterns" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="extensions" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="partialMatch" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="moveOperation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "moveFiles",
        "deleteDuplicateFiles",
        "useDefaultMatching",
        "movedFilePermissions",
        "mover"
    })
    public static class Movers {

        @XmlElement(defaultValue = "true")
        protected boolean moveFiles;
        @XmlElement(defaultValue = "false")
        protected boolean deleteDuplicateFiles;
        @XmlElement(defaultValue = "true")
        protected boolean useDefaultMatching;
        protected String movedFilePermissions;
        protected List<RsyncMover.Movers.Mover> mover;

        /**
         * Gets the value of the moveFiles property.
         * 
         */
        public boolean isMoveFiles() {
            return moveFiles;
        }

        /**
         * Sets the value of the moveFiles property.
         * 
         */
        public void setMoveFiles(boolean value) {
            this.moveFiles = value;
        }

        /**
         * Gets the value of the deleteDuplicateFiles property.
         * 
         */
        public boolean isDeleteDuplicateFiles() {
            return deleteDuplicateFiles;
        }

        /**
         * Sets the value of the deleteDuplicateFiles property.
         * 
         */
        public void setDeleteDuplicateFiles(boolean value) {
            this.deleteDuplicateFiles = value;
        }

        /**
         * Gets the value of the useDefaultMatching property.
         * 
         */
        public boolean isUseDefaultMatching() {
            return useDefaultMatching;
        }

        /**
         * Sets the value of the useDefaultMatching property.
         * 
         */
        public void setUseDefaultMatching(boolean value) {
            this.useDefaultMatching = value;
        }

        /**
         * Gets the value of the movedFilePermissions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMovedFilePermissions() {
            return movedFilePermissions;
        }

        /**
         * Sets the value of the movedFilePermissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMovedFilePermissions(String value) {
            this.movedFilePermissions = value;
        }

        /**
         * Gets the value of the mover property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mover property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMover().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RsyncMover.Movers.Mover }
         * 
         * 
         */
        public List<RsyncMover.Movers.Mover> getMover() {
            if (mover == null) {
                mover = new ArrayList<RsyncMover.Movers.Mover>();
            }
            return this.mover;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="targetDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="patterns" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="dontMatchPatterns" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="extensions" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="partialMatch" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="moveOperation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "targetDirectory",
            "patterns",
            "dontMatchPatterns",
            "extensions",
            "partialMatch",
            "moveOperation"
        })
        public static class Mover {

            protected String name;
            protected String targetDirectory;
            protected RsyncMover.Movers.Mover.Patterns patterns;
            protected RsyncMover.Movers.Mover.DontMatchPatterns dontMatchPatterns;
            protected RsyncMover.Movers.Mover.Extensions extensions;
            protected Boolean partialMatch;
            protected String moveOperation;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the targetDirectory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTargetDirectory() {
                return targetDirectory;
            }

            /**
             * Sets the value of the targetDirectory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTargetDirectory(String value) {
                this.targetDirectory = value;
            }

            /**
             * Gets the value of the patterns property.
             * 
             * @return
             *     possible object is
             *     {@link RsyncMover.Movers.Mover.Patterns }
             *     
             */
            public RsyncMover.Movers.Mover.Patterns getPatterns() {
                return patterns;
            }

            /**
             * Sets the value of the patterns property.
             * 
             * @param value
             *     allowed object is
             *     {@link RsyncMover.Movers.Mover.Patterns }
             *     
             */
            public void setPatterns(RsyncMover.Movers.Mover.Patterns value) {
                this.patterns = value;
            }

            /**
             * Gets the value of the dontMatchPatterns property.
             * 
             * @return
             *     possible object is
             *     {@link RsyncMover.Movers.Mover.DontMatchPatterns }
             *     
             */
            public RsyncMover.Movers.Mover.DontMatchPatterns getDontMatchPatterns() {
                return dontMatchPatterns;
            }

            /**
             * Sets the value of the dontMatchPatterns property.
             * 
             * @param value
             *     allowed object is
             *     {@link RsyncMover.Movers.Mover.DontMatchPatterns }
             *     
             */
            public void setDontMatchPatterns(RsyncMover.Movers.Mover.DontMatchPatterns value) {
                this.dontMatchPatterns = value;
            }

            /**
             * Gets the value of the extensions property.
             * 
             * @return
             *     possible object is
             *     {@link RsyncMover.Movers.Mover.Extensions }
             *     
             */
            public RsyncMover.Movers.Mover.Extensions getExtensions() {
                return extensions;
            }

            /**
             * Sets the value of the extensions property.
             * 
             * @param value
             *     allowed object is
             *     {@link RsyncMover.Movers.Mover.Extensions }
             *     
             */
            public void setExtensions(RsyncMover.Movers.Mover.Extensions value) {
                this.extensions = value;
            }

            /**
             * Gets the value of the partialMatch property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isPartialMatch() {
                return partialMatch;
            }

            /**
             * Sets the value of the partialMatch property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPartialMatch(Boolean value) {
                this.partialMatch = value;
            }

            /**
             * Gets the value of the moveOperation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMoveOperation() {
                return moveOperation;
            }

            /**
             * Sets the value of the moveOperation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMoveOperation(String value) {
                this.moveOperation = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "pattern"
            })
            public static class DontMatchPatterns {

                @XmlElement(required = true)
                protected List<String> pattern;

                /**
                 * Gets the value of the pattern property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the pattern property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPattern().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getPattern() {
                    if (pattern == null) {
                        pattern = new ArrayList<String>();
                    }
                    return this.pattern;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "extension"
            })
            public static class Extensions {

                @XmlElement(required = true)
                protected List<String> extension;

                /**
                 * Gets the value of the extension property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the extension property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getExtension().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getExtension() {
                    if (extension == null) {
                        extension = new ArrayList<String>();
                    }
                    return this.extension;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "pattern"
            })
            public static class Patterns {

                @XmlElement(required = true)
                protected List<String> pattern;

                /**
                 * Gets the value of the pattern property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the pattern property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPattern().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getPattern() {
                    if (pattern == null) {
                        pattern = new ArrayList<String>();
                    }
                    return this.pattern;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="downloadFiles" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="movedFilePermissions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="minimumFreeSpaceToDownload" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="mustMatchMoverForDownload" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="removePassivatedFilesIfNoLongerExistOnServer" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="passivateLocation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="depassivateEachTime" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="updateIntervalMinutes" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="server" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="pass" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="directories"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="directory" maxOccurs="unbounded" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="directory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="realDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="hostKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "downloadFiles",
        "movedFilePermissions",
        "minimumFreeSpaceToDownload",
        "mustMatchMoverForDownload",
        "removePassivatedFilesIfNoLongerExistOnServer",
        "passivateLocation",
        "depassivateEachTime",
        "updateIntervalMinutes",
        "server"
    })
    public static class Servers {

        @XmlElement(defaultValue = "false")
        protected boolean downloadFiles;
        protected String movedFilePermissions;
        @XmlElement(required = true, defaultValue = "0")
        protected String minimumFreeSpaceToDownload;
        @XmlElement(defaultValue = "false")
        protected boolean mustMatchMoverForDownload;
        @XmlElement(defaultValue = "true")
        protected boolean removePassivatedFilesIfNoLongerExistOnServer;
        @XmlElement(required = true)
        protected String passivateLocation;
        @XmlElement(defaultValue = "false")
        protected boolean depassivateEachTime;
        @XmlElement(defaultValue = "15")
        protected int updateIntervalMinutes;
        protected List<RsyncMover.Servers.Server> server;

        /**
         * Gets the value of the downloadFiles property.
         * 
         */
        public boolean isDownloadFiles() {
            return downloadFiles;
        }

        /**
         * Sets the value of the downloadFiles property.
         * 
         */
        public void setDownloadFiles(boolean value) {
            this.downloadFiles = value;
        }

        /**
         * Gets the value of the movedFilePermissions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMovedFilePermissions() {
            return movedFilePermissions;
        }

        /**
         * Sets the value of the movedFilePermissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMovedFilePermissions(String value) {
            this.movedFilePermissions = value;
        }

        /**
         * Gets the value of the minimumFreeSpaceToDownload property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMinimumFreeSpaceToDownload() {
            return minimumFreeSpaceToDownload;
        }

        /**
         * Sets the value of the minimumFreeSpaceToDownload property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMinimumFreeSpaceToDownload(String value) {
            this.minimumFreeSpaceToDownload = value;
        }

        /**
         * Gets the value of the mustMatchMoverForDownload property.
         * 
         */
        public boolean isMustMatchMoverForDownload() {
            return mustMatchMoverForDownload;
        }

        /**
         * Sets the value of the mustMatchMoverForDownload property.
         * 
         */
        public void setMustMatchMoverForDownload(boolean value) {
            this.mustMatchMoverForDownload = value;
        }

        /**
         * Gets the value of the removePassivatedFilesIfNoLongerExistOnServer property.
         * 
         */
        public boolean isRemovePassivatedFilesIfNoLongerExistOnServer() {
            return removePassivatedFilesIfNoLongerExistOnServer;
        }

        /**
         * Sets the value of the removePassivatedFilesIfNoLongerExistOnServer property.
         * 
         */
        public void setRemovePassivatedFilesIfNoLongerExistOnServer(boolean value) {
            this.removePassivatedFilesIfNoLongerExistOnServer = value;
        }

        /**
         * Gets the value of the passivateLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassivateLocation() {
            return passivateLocation;
        }

        /**
         * Sets the value of the passivateLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassivateLocation(String value) {
            this.passivateLocation = value;
        }

        /**
         * Gets the value of the depassivateEachTime property.
         * 
         */
        public boolean isDepassivateEachTime() {
            return depassivateEachTime;
        }

        /**
         * Sets the value of the depassivateEachTime property.
         * 
         */
        public void setDepassivateEachTime(boolean value) {
            this.depassivateEachTime = value;
        }

        /**
         * Gets the value of the updateIntervalMinutes property.
         * 
         */
        public int getUpdateIntervalMinutes() {
            return updateIntervalMinutes;
        }

        /**
         * Sets the value of the updateIntervalMinutes property.
         * 
         */
        public void setUpdateIntervalMinutes(int value) {
            this.updateIntervalMinutes = value;
        }

        /**
         * Gets the value of the server property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the server property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getServer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RsyncMover.Servers.Server }
         * 
         * 
         */
        public List<RsyncMover.Servers.Server> getServer() {
            if (server == null) {
                server = new ArrayList<RsyncMover.Servers.Server>();
            }
            return this.server;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="pass" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="directories"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="directory" maxOccurs="unbounded" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="directory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="realDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="hostKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "host",
            "port",
            "user",
            "pass",
            "directories",
            "hostKey"
        })
        public static class Server {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String host;
            @XmlElement(defaultValue = "22")
            protected int port;
            @XmlElement(required = true)
            protected String user;
            @XmlElement(required = true)
            protected String pass;
            @XmlElement(required = true)
            protected RsyncMover.Servers.Server.Directories directories;
            protected String hostKey;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the host property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHost() {
                return host;
            }

            /**
             * Sets the value of the host property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHost(String value) {
                this.host = value;
            }

            /**
             * Gets the value of the port property.
             * 
             */
            public int getPort() {
                return port;
            }

            /**
             * Sets the value of the port property.
             * 
             */
            public void setPort(int value) {
                this.port = value;
            }

            /**
             * Gets the value of the user property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUser() {
                return user;
            }

            /**
             * Sets the value of the user property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUser(String value) {
                this.user = value;
            }

            /**
             * Gets the value of the pass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPass() {
                return pass;
            }

            /**
             * Sets the value of the pass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPass(String value) {
                this.pass = value;
            }

            /**
             * Gets the value of the directories property.
             * 
             * @return
             *     possible object is
             *     {@link RsyncMover.Servers.Server.Directories }
             *     
             */
            public RsyncMover.Servers.Server.Directories getDirectories() {
                return directories;
            }

            /**
             * Sets the value of the directories property.
             * 
             * @param value
             *     allowed object is
             *     {@link RsyncMover.Servers.Server.Directories }
             *     
             */
            public void setDirectories(RsyncMover.Servers.Server.Directories value) {
                this.directories = value;
            }

            /**
             * Gets the value of the hostKey property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHostKey() {
                return hostKey;
            }

            /**
             * Sets the value of the hostKey property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHostKey(String value) {
                this.hostKey = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="directory" maxOccurs="unbounded" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="directory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="realDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "directory"
            })
            public static class Directories {

                protected List<RsyncMover.Servers.Server.Directories.Directory> directory;

                /**
                 * Gets the value of the directory property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the directory property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDirectory().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link RsyncMover.Servers.Server.Directories.Directory }
                 * 
                 * 
                 */
                public List<RsyncMover.Servers.Server.Directories.Directory> getDirectory() {
                    if (directory == null) {
                        directory = new ArrayList<RsyncMover.Servers.Server.Directories.Directory>();
                    }
                    return this.directory;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="directory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="realDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "directory",
                    "realDirectory"
                })
                public static class Directory {

                    @XmlElement(required = true)
                    protected String directory;
                    protected String realDirectory;

                    /**
                     * Gets the value of the directory property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDirectory() {
                        return directory;
                    }

                    /**
                     * Sets the value of the directory property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDirectory(String value) {
                        this.directory = value;
                    }

                    /**
                     * Gets the value of the realDirectory property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRealDirectory() {
                        return realDirectory;
                    }

                    /**
                     * Sets the value of the realDirectory property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRealDirectory(String value) {
                        this.realDirectory = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="watch" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "watch"
    })
    public static class Watches {

        @XmlElement(required = true)
        protected List<String> watch;

        /**
         * Gets the value of the watch property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the watch property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWatch().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getWatch() {
            if (watch == null) {
                watch = new ArrayList<String>();
            }
            return this.watch;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="webServer" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "webServer",
        "port"
    })
    public static class WebServer {

        protected boolean webServer;
        protected int port;

        /**
         * Gets the value of the webServer property.
         * 
         */
        public boolean isWebServer() {
            return webServer;
        }

        /**
         * Sets the value of the webServer property.
         * 
         */
        public void setWebServer(boolean value) {
            this.webServer = value;
        }

        /**
         * Gets the value of the port property.
         * 
         */
        public int getPort() {
            return port;
        }

        /**
         * Sets the value of the port property.
         * 
         */
        public void setPort(int value) {
            this.port = value;
        }

    }

}
